# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7592f8e8de2e561cfcf61af4260019b29e7c1bf117e67ab373b535836417d15853361cdd6c0a06e849539e37170c2361062513e41901753ac80d79c7c8ab5b6d

test:
  secret_key_base: 478724ab5fbf4d7511dd4ad5088dd2be9288eaaee3a47a38278aa456fefd7fca74aa716d3dda35fa26b7924f35e70a63e17876823b081d05754374259d11b60e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
